language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_install:
  - cd bpdashboard

before_scrip:
  - npm install -g exp

script:
  - npm test
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: surge
  skip_cleanup: true
  domain: bilpark-dashboard.surge.sh
  project: ./bpdashboard/build/
on:
  branch: master

notifications:
  email: false
  slack:
    rooms:
      - bachelor-it2901:GvHs8vnnvxJB8Rfb78EuRnJ8#travis
